### ISSUE TITLE
Exercício ChurrascoJS - Objetos, funções e DOM

### ISSUE THREAD

**Issue by diegoneri** [ermogenes/aulas-programacao-web#12]
---

## Exercício `ChurrascoJS`

Reimplementação em JavaScript do exercício `ChurrascoJS` da lista "Números e Operadores" do Dev C#: [Churrasco](https://github.com/ermogenes/aulas-programacao-csharp/blob/master/exercises/numeros-operadores.md#exerc%C3%ADcio-churrasco)

_Não recomendamos o uso de imagens as quais você não tenha direito de uso. Este curso se exime de qualquer responsabilidade referente a danos causados à terceiros em trabalhos criados por alunos_.

**Comment by ermogenes** [comment]
Resolvido
